BEGIN;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO housedb_app;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO housedb_app;

GRANT EXECUTE
ON ALL FUNCTIONS IN SCHEMA public
TO housedb_app;

GRANT EXECUTE
ON ALL ROUTINES IN SCHEMA public
TO housedb_app;

ALTER DEFAULT PRIVILEGES FOR ROLE flyway_migrator IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO housedb_app;

ALTER DEFAULT PRIVILEGES FOR ROLE flyway_migrator IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO housedb_app;

ALTER DEFAULT PRIVILEGES FOR ROLE flyway_migrator IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO housedb_app;

COMMIT;
